language: python
python:
  - "3.7"
addons:
  ssh_known_hosts: 68.183.94.49
before_install:
  - openssl aes-256-cbc -K $encrypted_0ddd2445e49f_key -iv $encrypted_0ddd2445e49f_iv
    -in travis_rsa.enc -out travis_rsa -d
  - chmod 600 travis_rsa
  - mv travis_rsa ~/.ssh/id_rsa
install:
  - pip install pipenv
  - pipenv install
  - echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDmwXogdW9VG9MwvKbP8vfRdrhusVH62jVkMSR7FdSNa1l4kYsaiDsCvrU2ptV16Zw+nUHsPxrqi0I8te2XWoVeYgizNZIn+0yZ2Bswbdu+iIz09fbPJRlfbB9hpstyh9Fw45Hiavpb6iverTGIppzssJlvISxHafRljID0o+rkRvK0fy08RhAtI7oVPj+xdp3yhTVjBJ2/i2m3iZ8iBa0BdeSw8WE6YdK4VPhQ2aeDsieTZnT9H5qCudrHmjCX2PAPL0vKR46hXn6DU/BoxmDdkNTiUlKeE4QANBo0Y+i3FPrpxI7qXIlFIsjRV4L/LNrJMc90zxYJegAvX36NwwUX abhi_ap@Abhi-Dell' >> $HOME/.ssh/known_hosts
services:
  - postgresql
before_script:
  - psql -c 'create database test_postgres_db;' -U postgres
script:
  - pytest
after_success:
  - bash ./deploy.sh
notifications:
  email:
    recipients:
      - abhi_ap@hotmail.com
    on_success: always
    on_failure: always
  slack:
    rooms:
      secure: jcMFufxytl+E68U8U3vH2bS/VPN9nSTCHGD/rTGkhY+27ZIgeWJe0gqHm/pBy4K6phA9ivWL1XCEigPOuFIZCv40cL5LqrEdJ+dgZTjRXxfTPT8S8ofvOHImWQZRU5DAufUjrV0EbNzZAGF16vVnWljT9t0eFhMIxMyyKTUVb6Bw02Z5d0ya/DISm90+68a4gkgQ+porbTQ06IYs35ViZ8eONZuaAEHp4tsguKslH0HSqdahWsiXdTfrGEhgAWf5yNAqQKaC8cd8YrPJzoI1zkr7ixL+FIBhcgQ/A6bHCTOVbiZ7McOq4n3Dtl+HZCKIOK274IsPNTybK+46stWANrOSodmmDCRxoLI0mK5S4eLLjRIydUpHqa0tEf5HScNjBoERv1gNCSrmW+tHEns4OAxuqtpJzvxcdb0JBQnStpvxzS/s1Q0/y83iEWzDjUUFmoBf9JySjjz0SMuvEsFUSHB300L207ifEKfmWHU5YDLIZOM/bCZV6fhG9+xIMXBMtOn9K3CjDHjosEtrROWiwENyv2hs3/i573Y6yHuMvibFjdyYfRGTrb8fbiQN3XaWnByUxvmc+K/CjANohImqv34rNJNvmLaPnqSifgOhbw5nF42RW4camp0Llgu5eZZq+VsS0jGscwuDnVpi+QRZ2nWw6Yj16Il4XwtYT7oosi0=
