"""Changed history to be a MuableList

Revision ID: 05fe8e739f69
Revises: f61fc25e6918
Create Date: 2021-02-01 11:50:03.232646

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "05fe8e739f69"
down_revision = "f61fc25e6918"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
