"""Added the apartment number column

Revision ID: 071cbe90ca80
Revises: 7a9e7f8c5c9a
Create Date: 2020-10-29 15:55:02.096433

"""
# import sqlalchemy as sa
# from alembic import op

# revision identifiers, used by Alembic.
revision = "071cbe90ca80"
down_revision = "7a9e7f8c5c9a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
