"""Reset the ads table

Revision ID: 0cd3d795a138
Revises: 4ea2520c031a
Create Date: 2020-11-18 13:28:01.722933

"""
# import sqlalchemy as sa
# from alembic import op
# revision identifiers, used by Alembic.
revision = "0cd3d795a138"
down_revision = "4ea2520c031a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
