"""Corrected relationship in the ad images table

Revision ID: 10dbcc4e828b
Revises: c0d3d58cdecf
Create Date: 2020-11-17 22:48:41.343351

"""
# import sqlalchemy as sa
# from alembic import op

# revision identifiers, used by Alembic.
revision = "10dbcc4e828b"
down_revision = "c0d3d58cdecf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
