"""Changed history to be a MuabledICT

Revision ID: 2107eb648957
Revises: 05fe8e739f69
Create Date: 2021-02-01 13:36:29.025242

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "2107eb648957"
down_revision = "05fe8e739f69"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
