"""Changed the datatype of multiple ad columns

Revision ID: 4ea2520c031a
Revises: 1a274c4ffaa9
Create Date: 2020-11-18 13:21:36.572690

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4ea2520c031a"
down_revision = "1a274c4ffaa9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ads",
        "ad_category",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
    op.alter_column(
        "ads", "ad_type", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ads", "ad_type", existing_type=sa.VARCHAR(length=15), nullable=True
    )
    op.alter_column(
        "ads", "ad_category", existing_type=sa.VARCHAR(length=20), nullable=True
    )
    # ### end Alembic commands ###
