"""Removed last_updated_on column

Revision ID: 4ed60b42bbf8
Revises: a87ed5a15470
Create Date: 2020-08-27 12:59:40.933183

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4ed60b42bbf8"
down_revision = "a87ed5a15470"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("apartments", "last_updated_on")
    op.drop_column("users", "last_updated_on")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "last_updated_on",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "apartments",
        sa.Column(
            "last_updated_on",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
