"""Recreate ads tables

Revision ID: 56a156e8f1bf
Revises: 82a142c5b62c
Create Date: 2020-11-18 13:34:21.678595

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "56a156e8f1bf"
down_revision = "82a142c5b62c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ads",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=10000), nullable=False),
        sa.Column("ad_category", sa.String(length=50), nullable=False),
        sa.Column("ad_type", sa.String(length=50), nullable=False),
        sa.Column("price", sa.Numeric(scale=2), nullable=True),
        sa.Column("negotiable", sa.Boolean(), nullable=True),
        sa.Column("condition", sa.String(length=50), nullable=True),
        sa.Column("available_from", sa.DateTime(), nullable=True),
        sa.Column("publish_flat_number", sa.Boolean(), nullable=True),
        sa.Column("posted_by", sa.Integer(), nullable=True),
        sa.Column("apartment_id", sa.Integer(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["apartment_id"], ["apartments.id"]),
        sa.ForeignKeyConstraint(["posted_by"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ads_ad_category"), "ads", ["ad_category"], unique=False
    )
    op.create_index(op.f("ix_ads_id"), "ads", ["id"], unique=False)
    op.create_table(
        "adimages",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("ad_id", sa.Integer(), nullable=True),
        sa.Column("image_path", sa.String(length=500), nullable=False),
        sa.ForeignKeyConstraint(["ad_id"], ["ads.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_adimages_id"), "adimages", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_adimages_id"), table_name="adimages")
    op.drop_table("adimages")
    op.drop_index(op.f("ix_ads_id"), table_name="ads")
    op.drop_index(op.f("ix_ads_ad_category"), table_name="ads")
    op.drop_table("ads")
    # ### end Alembic commands ###
