"""Changed mobile to a string

Revision ID: 580bff42880d
Revises: c1fce2c60107
Create Date: 2020-10-04 23:38:58.456993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "580bff42880d"
down_revision = "c1fce2c60107"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "mobile", existing_type=sa.VARCHAR(length=15), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "mobile", existing_type=sa.BIGINT, nullable=True)
    # ### end Alembic commands ###
