"""Added the chat history table

Revision ID: 6095e4934fee
Revises: 69c62cb602c4
Create Date: 2021-01-30 22:19:50.300727

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "6095e4934fee"
down_revision = "69c62cb602c4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "chats", ["chat_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "chats", type_="unique")
    # ### end Alembic commands ###
