"""Added the new_notifications column to the chat history table

Revision ID: 6630264acc92
Revises: 9b7992bfb002
Create Date: 2021-02-03 17:29:49.954664

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "6630264acc92"
down_revision = "9b7992bfb002"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chathistory",
        sa.Column("new_notifications", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chathistory", "new_notifications")
    # ### end Alembic commands ###
