"""Updated relationships in the Chat table

Revision ID: 69c62cb602c4
Revises: 604631bd4d57
Create Date: 2021-01-28 17:19:20.823014

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "69c62cb602c4"
down_revision = "604631bd4d57"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("chats_seller_id_fkey", "chats", type_="foreignkey")
    op.drop_constraint("chats_buyer_id_fkey", "chats", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "chats_buyer_id_fkey", "chats", "users", ["buyer_id"], ["id"]
    )
    op.create_foreign_key(
        "chats_seller_id_fkey", "chats", "users", ["seller_id"], ["id"]
    )
    # ### end Alembic commands ###
