"""Added the apartment number and apartment submitted by columns

Revision ID: 72ff7664d585
Revises: f66a3588733b
Create Date: 2020-10-27 23:32:29.511405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "72ff7664d585"
down_revision = "f66a3588733b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("apartments", "apartment_number")
    op.add_column(
        "users",
        sa.Column("apartment_number", sa.String(length=10), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "apartment_number")
    op.add_column(
        "apartments",
        sa.Column(
            "apartment_number",
            sa.VARCHAR(length=10),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
