"""Added default value for the apartment number

Revision ID: 7a9e7f8c5c9a
Revises: 72ff7664d585
Create Date: 2020-10-27 23:34:12.863867

"""
# from alembic import op
# import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7a9e7f8c5c9a"
down_revision = "72ff7664d585"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
