"""Changed the sale of ads.price

Revision ID: 82a142c5b62c
Revises: 0cd3d795a138
Create Date: 2020-11-18 13:32:25.122779

"""
# import sqlalchemy as sa
# from alembic import op
# revision identifiers, used by Alembic.
revision = "82a142c5b62c"
down_revision = "0cd3d795a138"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
