"""Added the otp_verification_timestamp column

Revision ID: 8ebbe13a1ec0
Revises: ca0d526fded2
Create Date: 2020-10-06 00:11:38.893147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8ebbe13a1ec0"
down_revision = "ca0d526fded2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("otp_verification_timestamp", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "otp_verification_timestamp")
    # ### end Alembic commands ###
