"""Added the email verification columns

Revision ID: 940cbd446490
Revises: 32e341ebd993
Create Date: 2020-09-30 19:34:40.276035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "940cbd446490"
down_revision = "32e341ebd993"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "email_verification_hash", sa.String(length=100), nullable=True
        ),
    )
    op.add_column(
        "users", sa.Column("email_verified", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email_verified")
    op.drop_column("users", "email_verification_hash")
    # ### end Alembic commands ###
