"""Added the sold and hash columns

Revision ID: 9b29ee0e3566
Revises: 56a156e8f1bf
Create Date: 2020-11-25 14:20:51.808115

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9b29ee0e3566"
down_revision = "56a156e8f1bf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ads", sa.Column("sold", sa.Boolean(), nullable=True))
    op.add_column(
        "apartments",
        sa.Column("verification_hash", sa.String(length=100), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("apartments", "verification_hash")
    op.drop_column("ads", "sold")
    # ### end Alembic commands ###
