"""Changed history to be a MuableList

Revision ID: 9b7992bfb002
Revises: 2107eb648957
Create Date: 2021-02-01 15:00:07.445246

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "9b7992bfb002"
down_revision = "2107eb648957"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
