"""Added mail_subscribed column

Revision ID: 9c01dc1fcd35
Revises: 4ed60b42bbf8
Create Date: 2020-09-12 00:48:51.292739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9c01dc1fcd35"
down_revision = "4ed60b42bbf8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("mail_subscribed", sa.Boolean(), nullable=True)
    )
    op.alter_column(
        "users", "last_name", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "last_name",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
    op.drop_column("users", "mail_subscribed")
    # ### end Alembic commands ###
