"""Changed the history datatype to JSONB

Revision ID: b6fa482266c4
Revises: faa2a97f51e6
Create Date: 2021-02-01 11:17:33.752447

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "b6fa482266c4"
down_revision = "faa2a97f51e6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
