"""Added the LikeAd table

Revision ID: bbd61da32aac
Revises: d3605bb09ed0
Create Date: 2020-12-15 15:39:38.651796

"""
# import sqlalchemy as sa
# from alembic import op
# revision identifiers, used by Alembic.
revision = "bbd61da32aac"
down_revision = "d3605bb09ed0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
