"""Added the ads tables

Revision ID: c0d3d58cdecf
Revises: 071cbe90ca80
Create Date: 2020-11-17 21:43:27.439131

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c0d3d58cdecf"
down_revision = "071cbe90ca80"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("ads_path", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "users", sa.Column("profile_path", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "profile_path")
    op.drop_column("users", "ads_path")
    # ### end Alembic commands ###
