"""Changed otp to string

Revision ID: ca0d526fded2
Revises: f18212f5ef04
Create Date: 2020-10-05 19:44:40.911863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ca0d526fded2"
down_revision = "f18212f5ef04"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "otp",
        existing_type=sa.Integer,
        type_=sa.String(length=6),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "otp",
        existing_type=sa.String(length=6),
        type_=sa.Integer,
        existing_nullable=True,
    )
    # ### end Alembic commands ###
