"""Removed uselist from the users models

Revision ID: caa15dfcd4b0
Revises: d7f36721aa13
Create Date: 2020-09-14 02:08:49.867320

"""
# from alembic import op
# import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "caa15dfcd4b0"
down_revision = "d7f36721aa13"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
