"""Added uselist to the User table

Revision ID: d7f36721aa13
Revises: 9c01dc1fcd35
Create Date: 2020-09-14 01:39:31.577211

"""
# from alembic import op
# import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d7f36721aa13"
down_revision = "9c01dc1fcd35"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
