"""Added the reportedads table

Revision ID: d86956ee02ab
Revises: 6630264acc92
Create Date: 2021-02-08 21:08:49.802322

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "d86956ee02ab"
down_revision = "6630264acc92"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reportedads", sa.Column("ad_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "reportedads",
        sa.Column("description", sa.String(length=5000), nullable=False),
    )
    op.add_column(
        "reportedads",
        sa.Column("reason", sa.String(length=100), nullable=False),
    )
    op.add_column(
        "reportedads", sa.Column("reported_by", sa.Integer(), nullable=True)
    )
    op.add_column(
        "reportedads", sa.Column("reported_on", sa.DateTime(), nullable=True)
    )
    op.create_index(
        op.f("ix_reportedads_ad_id"), "reportedads", ["ad_id"], unique=False
    )
    op.create_index(
        op.f("ix_reportedads_id"), "reportedads", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_reportedads_reported_by"),
        "reportedads",
        ["reported_by"],
        unique=False,
    )
    op.create_foreign_key(None, "reportedads", "ads", ["ad_id"], ["id"])
    op.create_foreign_key(None, "reportedads", "users", ["reported_by"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "reportedads", type_="foreignkey")
    op.drop_constraint(None, "reportedads", type_="foreignkey")
    op.drop_index(op.f("ix_reportedads_reported_by"), table_name="reportedads")
    op.drop_index(op.f("ix_reportedads_id"), table_name="reportedads")
    op.drop_index(op.f("ix_reportedads_ad_id"), table_name="reportedads")
    op.drop_column("reportedads", "reported_on")
    op.drop_column("reportedads", "reported_by")
    op.drop_column("reportedads", "reason")
    op.drop_column("reportedads", "description")
    op.drop_column("reportedads", "ad_id")
    # ### end Alembic commands ###
