"""Changed mobile to a string

Revision ID: f18212f5ef04
Revises: 580bff42880d
Create Date: 2020-10-04 23:44:59.723032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f18212f5ef04"
down_revision = "580bff42880d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "mobile",
        existing_type=sa.BIGINT,
        type_=sa.String(length=15),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "mobile",
        existing_type=sa.String(length=15),
        type_=sa.BIGINT,
        existing_nullable=True,
    )
    # ### end Alembic commands ###
