"""Added the apartment number column

Revision ID: f66a3588733b
Revises: 8ebbe13a1ec0
Create Date: 2020-10-27 23:28:55.929652

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f66a3588733b"
down_revision = "8ebbe13a1ec0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "apartments",
        sa.Column("apartment_number", sa.String(length=10), nullable=True),
    )
    op.add_column(
        "apartments",
        sa.Column("submitted_by", sa.String(length=50), nullable=True),
    )
    op.drop_column("apartments", "name_token")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "apartments",
        sa.Column(
            "name_token",
            postgresql.TSVECTOR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("apartments", "submitted_by")
    op.drop_column("apartments", "apartment_number")
    # ### end Alembic commands ###
