"""Updated the chat history table

Revision ID: faa2a97f51e6
Revises: 6095e4934fee
Create Date: 2021-01-30 22:21:55.733558

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "faa2a97f51e6"
down_revision = "6095e4934fee"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chathistory",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("chat_id", sa.String(length=64), nullable=False),
        sa.Column(
            "history", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.chat_id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chathistory_id"), "chathistory", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chathistory_id"), table_name="chathistory")
    op.drop_table("chathistory")
    # ### end Alembic commands ###
